/**
 * RCQI schema - AI analysis and semantic connections
 */

import { pgTable, serial, integer, varchar, text, decimal, boolean, timestamp, jsonb, index } from 'drizzle-orm/pg-core';
import { ayahs } from './quran';

export const rcqiAnalysisCache = pgTable('rcqi_analysis_cache', {
    id: serial('id').primaryKey(),
    ayahId: integer('ayah_id').notNull().references(() => ayahs.id),
    analysisType: varchar('analysis_type', { length: 50 }).notNull(), // 'root' | 'semantic' | 'thematic' | 'cross_reference'
    analysisVersion: varchar('analysis_version', { length: 20 }).notNull(),
    result: jsonb('result').$type<{
        roots?: Array<{
            rootId: number;
            word: string;
            derivatives: string[];
            semanticField: string;
            contextualMeaning: string;
        }>;
        themes?: string[];
        crossReferences?: number[];
        linguisticInsights?: string;
        confidence: number;
    }>().notNull(),
    tokensUsed: integer('tokens_used').default(0),
    processingTime: integer('processing_time'), // milliseconds
    createdAt: timestamp('created_at').defaultNow().notNull(),
    expiresAt: timestamp('expires_at'),
}, (table) => ({
    ayahTypeIdx: index('rcqi_ayah_type_idx').on(table.ayahId, table.analysisType),
    expiresIdx: index('rcqi_expires_idx').on(table.expiresAt),
}));

export const semanticConnections = pgTable('semantic_connections', {
    id: serial('id').primaryKey(),
    sourceAyahId: integer('source_ayah_id').notNull().references(() => ayahs.id),
    targetAyahId: integer('target_ayah_id').notNull().references(() => ayahs.id),
    connectionType: varchar('connection_type', { length: 50 }).notNull(), // 'thematic' | 'linguistic' | 'narrative' | 'legal'
    strength: decimal('strength', { precision: 3, scale: 2 }).notNull(), // 0.00 - 1.00
    description: text('description'),
    autoGenerated: boolean('auto_generated').default(true),
    createdBy: integer('created_by'), // user ID if manually created
    votes: integer('votes').default(0),
    metadata: jsonb('metadata').$type<{
        sharedRoots?: number[];
        sharedThemes?: string[];
        aiConfidence?: number;
    }>(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
}, (table) => ({
    sourceIdx: index('semantic_source_idx').on(table.sourceAyahId),
    targetIdx: index('semantic_target_idx').on(table.targetAyahId),
    typeIdx: index('semantic_type_idx').on(table.connectionType),
}));
