/**
 * RCQI Analysis types
 */

import type { AyahReference } from './quran';

export type AnalysisType = 'root' | 'semantic' | 'thematic' | 'cross_reference';

export interface RCQIAnalysis {
    id: string;
    ayahId: string;
    analysisType: AnalysisType;
    analysisVersion: string;
    result: RCQIAnalysisResult;
    tokensUsed: number;
    processingTime: number;
    createdAt: Date;
    expiresAt?: Date;
}

export interface RCQIAnalysisResult {
    roots?: RootAnalysisResult[];
    themes?: string[];
    crossReferences?: AyahReference[];
    linguisticInsights?: string;
    confidence: number;
}

export interface RootAnalysisResult {
    rootId: string;
    word: string;
    derivatives: string[];
    semanticField: string;
    contextualMeaning: string;
    occurrencesInQuran?: number;
}

export interface SemanticConnection {
    id: string;
    sourceAyahId: string;
    targetAyahId: string;
    connectionType: 'thematic' | 'linguistic' | 'narrative' | 'legal';
    strength: number; // 0-1
    description: string;
    autoGenerated: boolean;
    createdBy?: string;
    votes: number;
    metadata: {
        sharedRoots?: string[];
        sharedThemes?: string[];
        aiConfidence?: number;
    };
}

export interface SemanticSearchResult {
    ayahId: string;
    similarity: number;
    highlights: string[];
}

export interface AnalysisRequest {
    ayahId: string;
    analysisType: AnalysisType;
    options?: {
        forceRefresh?: boolean;
        includeRelated?: boolean;
        maxCrossReferences?: number;
    };
}

export interface AnalysisResponse {
    analysis: RCQIAnalysis;
    cached: boolean;
    processingTime: number;
}
