/**
 * Complete metadata for all 114 Quranic surahs
 */

export const surahMetadata: Record<number, { 
    english: string; 
    transliteration: string; 
    arabic: string;
    type: "meccan" | "medinan";
    verses: number;
}> = {
    1: { english: "The Opening", transliteration: "Al-Fatihah", arabic: "الفاتحة", type: "meccan", verses: 7 },
    2: { english: "The Cow", transliteration: "Al-Baqarah", arabic: "البقرة", type: "medinan", verses: 286 },
    3: { english: "The Family of Imran", transliteration: "Ali 'Imran", arabic: "آل عمران", type: "medinan", verses: 200 },
    4: { english: "The Women", transliteration: "An-Nisa", arabic: "النساء", type: "medinan", verses: 176 },
    5: { english: "The Table Spread", transliteration: "Al-Ma'idah", arabic: "المائدة", type: "medinan", verses: 120 },
    6: { english: "The Cattle", transliteration: "Al-An'am", arabic: "الأنعام", type: "meccan", verses: 165 },
    7: { english: "The Heights", transliteration: "Al-A'raf", arabic: "الأعراف", type: "meccan", verses: 206 },
    8: { english: "The Spoils of War", transliteration: "Al-Anfal", arabic: "الأنفال", type: "medinan", verses: 75 },
    9: { english: "The Repentance", transliteration: "At-Tawbah", arabic: "التوبة", type: "medinan", verses: 129 },
    10: { english: "Jonah", transliteration: "Yunus", arabic: "يونس", type: "meccan", verses: 109 },
    11: { english: "Hud", transliteration: "Hud", arabic: "هود", type: "meccan", verses: 123 },
    12: { english: "Joseph", transliteration: "Yusuf", arabic: "يوسف", type: "meccan", verses: 111 },
    13: { english: "The Thunder", transliteration: "Ar-Ra'd", arabic: "الرعد", type: "medinan", verses: 43 },
    14: { english: "Abraham", transliteration: "Ibrahim", arabic: "إبراهيم", type: "meccan", verses: 52 },
    15: { english: "The Rocky Tract", transliteration: "Al-Hijr", arabic: "الحجر", type: "meccan", verses: 99 },
    16: { english: "The Bee", transliteration: "An-Nahl", arabic: "النحل", type: "meccan", verses: 128 },
    17: { english: "The Night Journey", transliteration: "Al-Isra", arabic: "الإسراء", type: "meccan", verses: 111 },
    18: { english: "The Cave", transliteration: "Al-Kahf", arabic: "الكهف", type: "meccan", verses: 110 },
    19: { english: "Mary", transliteration: "Maryam", arabic: "مريم", type: "meccan", verses: 98 },
    20: { english: "Ta-Ha", transliteration: "Ta-Ha", arabic: "طه", type: "meccan", verses: 135 },
    21: { english: "The Prophets", transliteration: "Al-Anbiya", arabic: "الأنبياء", type: "meccan", verses: 112 },
    22: { english: "The Pilgrimage", transliteration: "Al-Hajj", arabic: "الحج", type: "medinan", verses: 78 },
    23: { english: "The Believers", transliteration: "Al-Mu'minun", arabic: "المؤمنون", type: "meccan", verses: 118 },
    24: { english: "The Light", transliteration: "An-Nur", arabic: "النور", type: "medinan", verses: 64 },
    25: { english: "The Criterion", transliteration: "Al-Furqan", arabic: "الفرقان", type: "meccan", verses: 77 },
    26: { english: "The Poets", transliteration: "Ash-Shu'ara", arabic: "الشعراء", type: "meccan", verses: 227 },
    27: { english: "The Ant", transliteration: "An-Naml", arabic: "النمل", type: "meccan", verses: 93 },
    28: { english: "The Stories", transliteration: "Al-Qasas", arabic: "القصص", type: "meccan", verses: 88 },
    29: { english: "The Spider", transliteration: "Al-Ankabut", arabic: "العنكبوت", type: "meccan", verses: 69 },
    30: { english: "The Romans", transliteration: "Ar-Rum", arabic: "الروم", type: "meccan", verses: 60 },
    31: { english: "Luqman", transliteration: "Luqman", arabic: "لقمان", type: "meccan", verses: 34 },
    32: { english: "The Prostration", transliteration: "As-Sajda", arabic: "السجدة", type: "meccan", verses: 30 },
    33: { english: "The Combined Forces", transliteration: "Al-Ahzab", arabic: "الأحزاب", type: "medinan", verses: 73 },
    34: { english: "Sheba", transliteration: "Saba", arabic: "سبأ", type: "meccan", verses: 54 },
    35: { english: "The Originator", transliteration: "Fatir", arabic: "فاطر", type: "meccan", verses: 45 },
    36: { english: "Ya-Sin", transliteration: "Ya-Sin", arabic: "يس", type: "meccan", verses: 83 },
    37: { english: "Those Who Set the Ranks", transliteration: "As-Saffat", arabic: "الصافات", type: "meccan", verses: 182 },
    38: { english: "Sad", transliteration: "Sad", arabic: "ص", type: "meccan", verses: 88 },
    39: { english: "The Troops", transliteration: "Az-Zumar", arabic: "الزمر", type: "meccan", verses: 75 },
    40: { english: "The Forgiver", transliteration: "Ghafir", arabic: "غافر", type: "meccan", verses: 85 },
    41: { english: "Fussilat", transliteration: "Fussilat", arabic: "فصلت", type: "meccan", verses: 54 },
    42: { english: "The Consultation", transliteration: "Ash-Shura", arabic: "الشورى", type: "meccan", verses: 53 },
    43: { english: "The Ornaments of Gold", transliteration: "Az-Zukhruf", arabic: "الزخرف", type: "meccan", verses: 89 },
    44: { english: "The Smoke", transliteration: "Ad-Dukhan", arabic: "الدخان", type: "meccan", verses: 59 },
    45: { english: "The Crouching", transliteration: "Al-Jathiya", arabic: "الجاثية", type: "meccan", verses: 37 },
    46: { english: "The Wind-Curved Sandhills", transliteration: "Al-Ahqaf", arabic: "الأحقاف", type: "meccan", verses: 35 },
    47: { english: "Muhammad", transliteration: "Muhammad", arabic: "محمد", type: "medinan", verses: 38 },
    48: { english: "The Victory", transliteration: "Al-Fath", arabic: "الفتح", type: "medinan", verses: 29 },
    49: { english: "The Private Chambers", transliteration: "Al-Hujurat", arabic: "الحجرات", type: "medinan", verses: 18 },
    50: { english: "Qaf", transliteration: "Qaf", arabic: "ق", type: "meccan", verses: 45 },
    51: { english: "The Winnowing Winds", transliteration: "Adh-Dhariyat", arabic: "الذاريات", type: "meccan", verses: 60 },
    52: { english: "The Mount", transliteration: "At-Tur", arabic: "الطور", type: "meccan", verses: 49 },
    53: { english: "The Star", transliteration: "An-Najm", arabic: "النجم", type: "meccan", verses: 62 },
    54: { english: "The Moon", transliteration: "Al-Qamar", arabic: "القمر", type: "meccan", verses: 55 },
    55: { english: "The Beneficent", transliteration: "Ar-Rahman", arabic: "الرحمن", type: "medinan", verses: 78 },
    56: { english: "The Inevitable", transliteration: "Al-Waqi'a", arabic: "الواقعة", type: "meccan", verses: 96 },
    57: { english: "The Iron", transliteration: "Al-Hadid", arabic: "الحديد", type: "medinan", verses: 29 },
    58: { english: "The Pleading Woman", transliteration: "Al-Mujadila", arabic: "المجادلة", type: "medinan", verses: 22 },
    59: { english: "The Exile", transliteration: "Al-Hashr", arabic: "الحشر", type: "medinan", verses: 24 },
    60: { english: "She That is to be Examined", transliteration: "Al-Mumtahanah", arabic: "الممتحنة", type: "medinan", verses: 13 },
    61: { english: "The Ranks", transliteration: "As-Saff", arabic: "الصف", type: "medinan", verses: 14 },
    62: { english: "The Congregation", transliteration: "Al-Jumu'ah", arabic: "الجمعة", type: "medinan", verses: 11 },
    63: { english: "The Hypocrites", transliteration: "Al-Munafiqun", arabic: "المنافقون", type: "medinan", verses: 11 },
    64: { english: "The Mutual Disillusion", transliteration: "At-Taghabun", arabic: "التغابن", type: "medinan", verses: 18 },
    65: { english: "The Divorce", transliteration: "At-Talaq", arabic: "الطلاق", type: "medinan", verses: 12 },
    66: { english: "The Prohibition", transliteration: "At-Tahrim", arabic: "التحريم", type: "medinan", verses: 12 },
    67: { english: "The Sovereignty", transliteration: "Al-Mulk", arabic: "الملك", type: "meccan", verses: 30 },
    68: { english: "The Pen", transliteration: "Al-Qalam", arabic: "القلم", type: "meccan", verses: 52 },
    69: { english: "The Reality", transliteration: "Al-Haqqah", arabic: "الحاقة", type: "meccan", verses: 52 },
    70: { english: "The Ascending Stairways", transliteration: "Al-Ma'arij", arabic: "المعارج", type: "meccan", verses: 44 },
    71: { english: "Noah", transliteration: "Nuh", arabic: "نوح", type: "meccan", verses: 28 },
    72: { english: "The Jinn", transliteration: "Al-Jinn", arabic: "الجن", type: "meccan", verses: 28 },
    73: { english: "The Enshrouded One", transliteration: "Al-Muzzammil", arabic: "المزمل", type: "meccan", verses: 20 },
    74: { english: "The Cloaked One", transliteration: "Al-Muddaththir", arabic: "المدثر", type: "meccan", verses: 56 },
    75: { english: "The Resurrection", transliteration: "Al-Qiyamah", arabic: "القيامة", type: "meccan", verses: 40 },
    76: { english: "The Man", transliteration: "Al-Insan", arabic: "الإنسان", type: "medinan", verses: 31 },
    77: { english: "The Emissaries", transliteration: "Al-Mursalat", arabic: "المرسلات", type: "meccan", verses: 50 },
    78: { english: "The Tidings", transliteration: "An-Naba", arabic: "النبأ", type: "meccan", verses: 40 },
    79: { english: "Those Who Drag Forth", transliteration: "An-Nazi'at", arabic: "النازعات", type: "meccan", verses: 46 },
    80: { english: "He Frowned", transliteration: "'Abasa", arabic: "عبس", type: "meccan", verses: 42 },
    81: { english: "The Overthrowing", transliteration: "At-Takwir", arabic: "التكوير", type: "meccan", verses: 29 },
    82: { english: "The Cleaving", transliteration: "Al-Infitar", arabic: "الإنفطار", type: "meccan", verses: 19 },
    83: { english: "The Defrauding", transliteration: "Al-Mutaffifin", arabic: "المطففين", type: "meccan", verses: 36 },
    84: { english: "The Sundering", transliteration: "Al-Inshiqaq", arabic: "الإنشقاق", type: "meccan", verses: 25 },
    85: { english: "The Mansions of the Stars", transliteration: "Al-Buruj", arabic: "البروج", type: "meccan", verses: 22 },
    86: { english: "The Nightcomer", transliteration: "At-Tariq", arabic: "الطارق", type: "meccan", verses: 17 },
    87: { english: "The Most High", transliteration: "Al-A'la", arabic: "الأعلى", type: "meccan", verses: 19 },
    88: { english: "The Overwhelming", transliteration: "Al-Ghashiyah", arabic: "الغاشية", type: "meccan", verses: 26 },
    89: { english: "The Dawn", transliteration: "Al-Fajr", arabic: "الفجر", type: "meccan", verses: 30 },
    90: { english: "The City", transliteration: "Al-Balad", arabic: "البلد", type: "meccan", verses: 20 },
    91: { english: "The Sun", transliteration: "Ash-Shams", arabic: "الشمس", type: "meccan", verses: 15 },
    92: { english: "The Night", transliteration: "Al-Layl", arabic: "الليل", type: "meccan", verses: 21 },
    93: { english: "The Morning Hours", transliteration: "Ad-Duha", arabic: "الضحى", type: "meccan", verses: 11 },
    94: { english: "The Relief", transliteration: "Ash-Sharh", arabic: "الشرح", type: "meccan", verses: 8 },
    95: { english: "The Fig", transliteration: "At-Tin", arabic: "التين", type: "meccan", verses: 8 },
    96: { english: "The Clot", transliteration: "Al-'Alaq", arabic: "العلق", type: "meccan", verses: 19 },
    97: { english: "The Power", transliteration: "Al-Qadr", arabic: "القدر", type: "meccan", verses: 5 },
    98: { english: "The Clear Proof", transliteration: "Al-Bayyinah", arabic: "البينة", type: "medinan", verses: 8 },
    99: { english: "The Earthquake", transliteration: "Az-Zalzalah", arabic: "الزلزلة", type: "medinan", verses: 8 },
    100: { english: "The Courser", transliteration: "Al-'Adiyat", arabic: "العاديات", type: "meccan", verses: 11 },
    101: { english: "The Calamity", transliteration: "Al-Qari'ah", arabic: "القارعة", type: "meccan", verses: 11 },
    102: { english: "The Rivalry in World Increase", transliteration: "At-Takathur", arabic: "التكاثر", type: "meccan", verses: 8 },
    103: { english: "The Declining Day", transliteration: "Al-'Asr", arabic: "العصر", type: "meccan", verses: 3 },
    104: { english: "The Traducer", transliteration: "Al-Humazah", arabic: "الهمزة", type: "meccan", verses: 9 },
    105: { english: "The Elephant", transliteration: "Al-Fil", arabic: "الفيل", type: "meccan", verses: 5 },
    106: { english: "Quraysh", transliteration: "Quraysh", arabic: "قريش", type: "meccan", verses: 4 },
    107: { english: "The Small Kindnesses", transliteration: "Al-Ma'un", arabic: "الماعون", type: "meccan", verses: 7 },
    108: { english: "The Abundance", transliteration: "Al-Kawthar", arabic: "الكوثر", type: "meccan", verses: 3 },
    109: { english: "The Disbelievers", transliteration: "Al-Kafirun", arabic: "الكافرون", type: "meccan", verses: 6 },
    110: { english: "The Divine Support", transliteration: "An-Nasr", arabic: "النصر", type: "medinan", verses: 3 },
    111: { english: "The Palm Fiber", transliteration: "Al-Masad", arabic: "المسد", type: "meccan", verses: 5 },
    112: { english: "The Sincerity", transliteration: "Al-Ikhlas", arabic: "الإخلاص", type: "meccan", verses: 4 },
    113: { english: "The Daybreak", transliteration: "Al-Falaq", arabic: "الفلق", type: "meccan", verses: 5 },
    114: { english: "Mankind", transliteration: "An-Nas", arabic: "الناس", type: "meccan", verses: 6 },
};
